// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTJAr32133wUijPaQMtOu_7sl8ZyXAgdw',
    appId: '1:380826005028:web:0dd328ed1e559a9aa432b1',
    messagingSenderId: '380826005028',
    projectId: 'mybook-ec027',
    authDomain: 'mybook-ec027.firebaseapp.com',
    storageBucket: 'mybook-ec027.appspot.com',
    measurementId: 'G-7C8383Q86D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6jOOk_MGnJsIsjwpn39u1H9kWBnM-_Aw',
    appId: '1:380826005028:android:78374039e19973b9a432b1',
    messagingSenderId: '380826005028',
    projectId: 'mybook-ec027',
    storageBucket: 'mybook-ec027.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMfjidWwboZzmxDbFqpkrvzpJ3lhEfcvs',
    appId: '1:380826005028:ios:d0d2ec3cdf284f1aa432b1',
    messagingSenderId: '380826005028',
    projectId: 'mybook-ec027',
    storageBucket: 'mybook-ec027.appspot.com',
    iosBundleId: 'com.example.mybook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMfjidWwboZzmxDbFqpkrvzpJ3lhEfcvs',
    appId: '1:380826005028:ios:d0d2ec3cdf284f1aa432b1',
    messagingSenderId: '380826005028',
    projectId: 'mybook-ec027',
    storageBucket: 'mybook-ec027.appspot.com',
    iosBundleId: 'com.example.mybook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTJAr32133wUijPaQMtOu_7sl8ZyXAgdw',
    appId: '1:380826005028:web:6d179b920c55c379a432b1',
    messagingSenderId: '380826005028',
    projectId: 'mybook-ec027',
    authDomain: 'mybook-ec027.firebaseapp.com',
    storageBucket: 'mybook-ec027.appspot.com',
    measurementId: 'G-T53J4VL4HD',
  );

}